# Generated by Django 4.2.16 on 2024-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdcounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
    ]
