# Generated by Django 4.2.16 on 2024-09-09 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birdcounter', '0002_alter_pdfdocument_file_alter_pdfdocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
