# Generated by Django 4.2.16 on 2024-09-09 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birdcounter', '0003_alter_pdfdocument_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
