# Generated by Django 4.2.16 on 2024-09-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdcounter', '0004_alter_pdfdocument_user'),
    ]

    operations = [
    ]
